spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///appinfodb
    username: root
    password: root1234

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: utf-8
  redis:
    database: 0
    host: 47.106.139.233
    port: 6379
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0
    timeout: 10000
mybatis:
  type-aliases-package: com.jack.appinfo.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql